name: Get arXiv papers (fix)
on:
  workflow_dispatch:

jobs:
  get-and-print:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v6

    - name: Run script
      run: |
        uv run fix.py
